// Purpose: Export route names for the app.
const routeNames  = {
    TEAM_PARAMS : 'TEAM_PARAMS', //route vide contenant un enfant
    SPRINT : 'SPRINT',
    HOME_PAGE : 'HOME_PAGE',
    PRESENTATION_FORM : 'PRESENTATION_FORM',
    ETUDIANTS : 'ETUDIANTS',
    LOGIN : 'LOGIN',
    REDIRECT : 'REDIRECT',
    TEMPLOGGED: 'TEMPLOGGED',
    LISTE_EQUIPES_VUE : 'LISTE_EQUIPES_VUE',
    CREATETEAM: 'CREATETEAM',
    NOTES: 'NOTES',
    NOTATION_EQUIPE: 'NOTATION_EQUIPE',
    TEST: 'TEST',
    BONUS_MALUS_TM : 'BONUS_MALUS_TM',
    NOTATION_EQUIPE_TM: 'NOTATION_EQUIPE_TM',
    ECHELLE_NOTES : 'ECHELLE_NOTES',
    SIGNALEMENT: 'SIGNALEMENT',
    BONUS_MALUS_SS: 'BONUS_MALUS_SS',
    QUESTIONS: 'QUESTIONS',
}

export default routeNames